### ISSUE TITLE
Error while running EVSchoolsDetect

### ISSUE THREAD

**Issue by JoseCansec** [AustralianAntarcticDivision/EchoviewR#14]
Hello

My name is Jose Canseco and I am currently post-processing krill acoustic data using the swarm detection method by applying EVSchoolsDetect. I had already ran the analysis and exported the csv file in Echoview 10. However, I had to re-analyze the data using a higher maximum threshold but I get the following error:

Error in if (EV_version > 11) { : argument is of length zero

I think it may be the Echoview version that I am currenlty using: Echoview11.1 but I am not sure. Do you have any suggestions, ideas or had already seen the problem?

Best regards, 
Jose

**Comment by raymondben** [comment]
Hi @JoseCansec . Looks like we aren't detecting the Echoview version correctly. Could you please copy and paste the output of
```
EVApp <- StartEchoview()
str(EVApp[['Version']])
```
and if that is NULL or empty, what is the output of `str(EVApp, max.level = 2)` ? Thanks

**Comment by martinjamescox** [comment]
Dear @JoseCansec .  I have just tried to fix this bug.  If you are happy to do a little testing, please get the latest version of EchoviewR (v 1.1.20) from this repo, and rerun your code.  Please let us know what happens.  Thanks

**Comment by JoseCansec** [comment]
Dear Ben and Martin

Thank you for your answer, the EVSchoolsDetect function seems to be working
well. I will get back to you if i find more issues.

Best regards,
Jose

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
