### ISSUE TITLE
Warning in install.packages : package ‘echoviewr’ is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by davidcglover** [AustralianAntarcticDivision/EchoviewR#2]
Attempting to install through RStudio. Should I use a different approach?

**Comment by martinjamescox** [comment]
I have just updated the EchoviewR GitHub readme with installation instructions.  Please let me know how you get on.

**Comment by davidcglover** [comment]
I will give it a try today. I really appreciate it!

Dave

David Glover, PhD
Fish Biologist
U.S. Fish and Wildlife Conservation Office
9053 Route 148, Suite A
Marion, IL 62959
Office: 618-997-6869; 105
Mobile: 618-579-4872
Fax: 618-997-9185

On May 13, 2017, at 3:44 AM, Martin Cox <notifications@github.com> wrote:

I have just updated the EchoviewR GitHub readme with installation
instructions. Please let me know how you get on.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AustralianAntarcticDivision/EchoviewR/issues/2#issuecomment-301234658>,
or mute the thread

**Comment by davidcglover** [comment]
After downloading "EchoviewR-master.zip" to the desktop, I used the following code to successfully install the library:

setwd("C:/Users/Desktop/")
unzip("EchoviewR-master.zip")
file.rename("EchoviewR-master", "EchoviewR")
shell("R CMD build EchoviewR")
install.packages("EchoviewR_1.0.tar.gz", repos=NULL)

Probably easier ways to do it, but I'm a fairly new user of R. Looking forward to using the library!
