### ISSUE TITLE
Installing EchoviewR

### ISSUE THREAD

**Issue by LaurieMaynard** [AustralianAntarcticDivision/EchoviewR#20]
I get this error while trying to install EchoviewR

ERROR: dependency 'rgeos' is not available for package 'EchoviewR'

Are you planning to update the package now that _rgeos_ has been removed from CRAN?
I managed by reinstalling an Archive version of _rgeos_ for now (https://cran.r-project.org/src/contrib/Archive/rgeos/).

Thank you.

**Comment by raymondben** [comment]
Hi @LaurieMaynard , thanks for the note. This should be fixed in v1.2.0 - would you mind testing (reinstalling) please if you have a chance? (Ideally `remove.packages("rgeos")` first.)

**Comment by LaurieMaynard** [comment]
Installation went very well.

Thank you!

Also thank you for providing such a tool. It's very useful.
