### ISSUE TITLE
Some functions not loading

### ISSUE THREAD

**Issue by davidcglover** [AustralianAntarcticDivision/EchoviewR#3]
"Error: could not find function" messages for EVNewFixedDepthLine and EVNewLineRelativeRegion. There may be other functions not loading as these are just a few of the ones I've tried using so far. I reinstalled library using instructions from github readme file, but this did not fix the problem.

**Comment by martinjamescox** [comment]
I think this is a Namespace issue.  The functions EVNewFixedDepthLine() and EVNewLineRelativeRegion() should now be included in the EchoviewR namespace and available for use. Please let me know how you get on.

**Comment by davidcglover** [comment]
It appears to be finding the functions just fine now, but I am receiving different error messages: 
"Error in EVFile[["Lines"]] : subscript out of bounds"
"Error in EVFile[["Variables"]] : subscript out of bounds"

**Comment by martinjamescox** [comment]
Could you please send me some more details?  For example, which functions have this error?  Thank you

**Comment by raymondben** [comment]
@davidcglover - please also paste the output of `sessionInfo()` - this is often useful for identifying e.g. dependency issues
