### ISSUE TITLE
EchoviewR’ is not available (for R version 2.14.0)

### ISSUE THREAD

**Issue by zfilander** [AustralianAntarcticDivision/EchoviewR#4]
Hi there,

I am trying to install EchoviewR (by running codes you had listed) but I am receiving this error message: **EchoviewR’ is not available (for R version 2.14.0)**. I had to downgrade to this version of R because the COMCleint package is not available for most recent versions of R (well I couldn't find one on the Omegahut website).

So my question is, is there a version of EchoviewR that is compatible for R 2.1.4.0?  Your guidance and assistance will be greatly appreciated.

Zoleka
(South Africa)

**Comment by martinjamescox** [comment]
Dear Zoleka, please provide the output of sessionInfo() so we can take a look at this.

**Comment by zfilander** [comment]
Hi Martin,

Thank you for your response...I am, however, getting a different error message from before- despite running the same code..The output of session below:


> install.packages(c("fields", "sp", "geosphere", "maptools", "RDCOMClient", "rgeos"))
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/2.14
Installing package(s) into ‘C:/Users/user/Documents/R/win-library/2.14’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/2.14
Warning in install.packages :
  package ‘RDCOMClient’ is not available (for R version 2.14.0)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/2.14/fields_6.7.zip'
Content type 'application/zip' length 2819121 bytes (2.7 Mb)
opened URL
downloaded 2.7 Mb

trying URL 'https://cran.rstudio.com/bin/windows/contrib/2.14/sp_1.0-8.zip'
Content type 'application/zip' length 1134549 bytes (1.1 Mb)
opened URL
downloaded 1.1 Mb

trying URL 'https://cran.rstudio.com/bin/windows/contrib/2.14/geosphere_1.2-28.zip'
Content type 'application/zip' length 1576657 bytes (1.5 Mb)
opened URL
downloaded 1.5 Mb

trying URL 'https://cran.rstudio.com/bin/windows/contrib/2.14/maptools_0.8-23.zip'
Content type 'application/zip' length 1065647 bytes (1.0 Mb)
opened URL
downloaded 1.0 Mb

trying URL 'https://cran.rstudio.com/bin/windows/contrib/2.14/rgeos_0.2-15.zip'
Content type 'application/zip' length 1611907 bytes (1.5 Mb)
opened URL
downloaded 1.5 Mb

package ‘fields’ successfully unpacked and MD5 sums checked
package ‘sp’ successfully unpacked and MD5 sums checked
package ‘geosphere’ successfully unpacked and MD5 sums checked
package ‘maptools’ successfully unpacked and MD5 sums checked
package ‘rgeos’ successfully unpacked and MD5 sums checked

The downloaded packages are in
	C:\Users\user\AppData\Local\Temp\RtmpG4ln1E\downloaded_packages
> if (!requireNamespace("devtools",quietly=TRUE)) install.packages("devtools")
Loading required namespace: devtools
> devtools::install_github('AustralianAntarcticDivision/EchoviewR')
Installing github repo(s) AustralianAntarcticDivision/EchoviewR/master from hadley
Installing AustralianAntarcticDivision/EchoviewR.zip from https://github.com/hadley/AustralianAntarcticDivision/EchoviewR/zipball
Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
  cannot open file 'C:\Users\user\AppData\Local\Temp\RtmpG4ln1E/AustralianAntarcticDivision/EchoviewR.zip': No such file or directory

**Comment by martinjamescox** [comment]
Hi Zoleka, I have just updated EchoviewR for R v3.4.1 .  I suggest you try again with R v3.4.1 and reinstall the EchoviewR package dependencies  along with devtools. Once you have done this, please run the R command `sessionInfo()` and paste the output in your reply.

**Comment by raymondben** [comment]
AFAIK, RDCOMClient is no longer available as a binary package from omegahat, and was never on CRAN. Thus, neither `install.packages("RDCOMClient")` (which is using CRAN) nor `install.packages("RDCOMClient", repos = "http://www.omegahat.org/R")` (from omergahat) will work?

It should presumably be possible to install from github (not tested!):
`devtools::install_github('omegahat/RDCOMClient')`
but note that this is a source package that will require the additional rtools to be installed. RStudio will do this if you don't have them. 

Update: Ah, I see: RDCOMClient is on CRANextras. For the record then, if you don't have CRANextras as one of your default repos, do:
`install.packages("RDCOMClient",repos="http://www.stats.ox.ac.uk/pub/RWin")`
This is a binary package, so doesn't require rtools as does the install_github option above.

**Comment by zfilander** [comment]
Hi Martin,

Thanks for your assistance, all packages are installed successfully, see output below:


> install.packages(c('fields','sp','geosphere','maptools','RDCOMClient','rgeos'))
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Installing packages into ‘C:/Users/user/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/fields_9.0.zip'
Content type 'application/zip' length 3610901 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/sp_1.2-5.zip'
Content type 'application/zip' length 1538315 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/geosphere_1.5-5.zip'
Content type 'application/zip' length 885033 bytes (864 KB)
downloaded 864 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/maptools_0.9-2.zip'
Content type 'application/zip' length 1823743 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/RDCOMClient_0.93-0.2.zip'
Content type 'application/zip' length 586324 bytes (572 KB)
downloaded 572 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rgeos_0.3-23.zip'
Content type 'application/zip' length 1724431 bytes (1.6 MB)
downloaded 1.6 MB

package ‘fields’ successfully unpacked and MD5 sums checked
package ‘sp’ successfully unpacked and MD5 sums checked
package ‘geosphere’ successfully unpacked and MD5 sums checked
package ‘maptools’ successfully unpacked and MD5 sums checked
package ‘RDCOMClient’ successfully unpacked and MD5 sums checked
package ‘rgeos’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\Rtmpq44eXq\downloaded_packages
> if (!requireNamespace("devtools",quietly=TRUE)) install.packages("devtools")
Installing package into ‘C:/Users/user/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘mime’, ‘curl’, ‘openssl’, ‘R6’, ‘httr’, ‘memoise’, ‘whisker’, ‘digest’, ‘rstudioapi’, ‘jsonlite’, ‘git2r’, ‘withr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mime_0.5.zip'
Content type 'application/zip' length 38033 bytes (37 KB)
downloaded 37 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/curl_2.7.zip'
Content type 'application/zip' length 3095225 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/openssl_0.9.6.zip'
Content type 'application/zip' length 3568433 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/R6_2.2.2.zip'
Content type 'application/zip' length 316790 bytes (309 KB)
downloaded 309 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/httr_1.2.1.zip'
Content type 'application/zip' length 281602 bytes (275 KB)
downloaded 275 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/memoise_1.1.0.zip'
Content type 'application/zip' length 29971 bytes (29 KB)
downloaded 29 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/whisker_0.3-2.zip'
Content type 'application/zip' length 64988 bytes (63 KB)
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/digest_0.6.12.zip'
Content type 'application/zip' length 173023 bytes (168 KB)
downloaded 168 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rstudioapi_0.6.zip'
Content type 'application/zip' length 51201 bytes (50 KB)
downloaded 50 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jsonlite_1.5.zip'
Content type 'application/zip' length 1159936 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.18.0.zip'
Content type 'application/zip' length 3053963 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_1.0.2.zip'
Content type 'application/zip' length 44164 bytes (43 KB)
downloaded 43 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.2.zip'
Content type 'application/zip' length 443150 bytes (432 KB)
downloaded 432 KB

package ‘mime’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\Rtmpq44eXq\downloaded_packages
> devtools::install_github('AustralianAntarcticDivision/EchoviewR')
Downloading GitHub repo AustralianAntarcticDivision/EchoviewR@master
from URL https://api.github.com/repos/AustralianAntarcticDivision/EchoviewR/zipball/master
Installing EchoviewR
"C:/PROGRA~1/R/R-34~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/user/AppData/Local/Temp/Rtmpq44eXq/devtools1f30711020e3/AustralianAntarcticDivision-EchoviewR-7bd84f0"  \
  --library="C:/Users/user/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'EchoviewR' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (EchoviewR)

**Comment by martinjamescox** [comment]
Hi Zoleka, pleased it worked.  I am going to close this issue now.
