### ISSUE TITLE
PDF Vignettes?

### ISSUE THREAD

**Issue by bethphillips** [AustralianAntarcticDivision/EchoviewR#5]
Hello,

I have successfully installed EchoviewR and downloaded the .zip file with data sets to run through the vignettes; however, I can't actually find any of the three PDF vignettes mentioned in the Description here ("The three pdf vignettes contain examples of reading data using EchoviewR, conducting school detection and running biomass estimation of Antarctic Krill."): https://data.aad.gov.au/metadata/records/AAS_4102_4104_4050_EchoviewR 

Are these available somewhere?

Thank you,
Elizabeth

**Comment by raymondben** [comment]
Hi Elizabeth - I made a few minor tweaks, and you can now browse the package docs and vignette at http://australianantarcticdivision.github.io/EchoviewR/index.html

There only seems to be one vignette, though - I'm not sure where the "three" vignettes are. @martinjamescox or @SvenGastauer might know?

(Edit: fixed link)

**Comment by ElizabethMPhillips** [comment]
Thanks! If others know where the three specific vignettes are located, that would be helpful.
