### ISSUE TITLE
Error with EVFindFilesetByName

### ISSUE THREAD

**Issue by dcorr039** [AustralianAntarcticDivision/EchoviewR#8]
Hello, I have an error using the function EVFilesInFileset. If I use EVFilesInFileset on a blank fileset I expect to get 'none' or 0. What I get is the following error: 
" Error in fileset.loc[["DataFiles"]]$Item(i)$FileName() : 
  attempt to apply non-function "

Might I suggest adding a statement to bypass this error if nbr.of.raw.in.fileset = 0

**Comment by raymondben** [comment]
fixed (yet to test)
